### ISSUE TITLE
How to use for Angular 1.x?

### ISSUE THREAD

**Issue by kozo96** [tiberiuzuld/angular-gridster2#201]
I haven't worked beyond Angular 1.x but I'm guessing this error is due to not having Angular 2:
`Uncaught TypeError: angular.module(...).component is not a function`

Is there any documentation for how to use gridster2 on Angular 1.x?

**Comment by tiberiuzuld** [comment]
Hi @kozo96 ,
You need to use 1.x branch for angular1.
For npm the latest version is 1.20.0.

Thanks

**Comment by kozo96** [comment]
I did, but angular source code for 1.x branch still has **angular.module(...).component**.

which gives me the same error:

> Uncaught TypeError: angular.module(...).component is not a function

**Comment by tiberiuzuld** [comment]
You need angular 1.5 at least.

**Comment by idreeshaddad** [comment]
Is there away to make it work on angular 1.3.2? Because upgrading will break lots of code :s

**Comment by tiberiuzuld** [comment]
Look over https://github.com/tiberiuzuld/angular-gridster2/pull/155
